# Generated by Django 2.1.4 on 2019-01-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitor_pdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituicao',
            name='pagina_final',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='constituicao',
            name='pagina_inicial',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='constituicao',
            name='trecho',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
