# Generated by Django 2.1.4 on 2019-01-06 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leitor_pdf', '0002_auto_20190106_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constituicao',
            name='pagina_final',
        ),
        migrations.RemoveField(
            model_name='constituicao',
            name='pagina_inicial',
        ),
    ]
