# Generated by Django 2.1.4 on 2019-01-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitor_pdf', '0003_auto_20190106_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituicao',
            name='pagina_inicial',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
